create table plano (
	dia 			integer,
	corr_ac1 		integer,
	carga_ac1 		real,
	corr_ac2 		integer,
	carga_ac2 		real,
	corr_transf 	integer,
	producao_aco 	real,	
	saldo 			real,
	psuc_ac1 		real,
	psuc_ac2 		real,
	psuc_tot	 	real,	
	prod_af1 		real,
	prod_af2 		real,
	prod_af3 		real,
	prod_af 		real,
	restr_hic 		integer,
	restr_dr 		integer,
	restr_rh 		integer,
	restr_fp2 		integer,
	aco_rh_tot 		real,
	aco_fp2_tot 	real,
	restr_fp1 		integer,
	aco_fp1_tot 	real	
)